# Generated by Django 5.0.2 on 2024-02-26 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naztify', '0002_user_name_alter_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCreate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='password',
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='aaa', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
