# Generated by Django 5.0.2 on 2024-02-28 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naztify', '0003_usercreate_rename_name_user_password_user_username_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyUpdateSubscription',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='naztify.user')),
                ('token', models.CharField(max_length=250)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
